# Generated by Django 4.1.2 on 2022-11-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="courtBooked",
        ),
    ]
