# Generated by Django 4.1.2 on 2022-10-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
