# Generated by Django 4.1.2 on 2022-11-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_customuser_courtbooked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
