# Generated by Django 4.1.2 on 2022-11-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
