# Generated by Django 4.0.6 on 2023-03-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
